// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "go.opentelemetry.io/collector/cmd/builder". DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

const (
	Type               = "custommetricencoding"
	ExtensionStability = component.StabilityLevelAlpha
)
